input ("hello: ")
input ("what is your name: ")
input ("my name is gio: ")
input ("where are you from: ")
input ("i am also from georgia:")
input ("how old are you: ")
input ("a am 14 yers old: ")
input ("nice to meet you: ")
input ("good bye: ")